plainTextContentType={
    "Content-Type":"text/plain"
}
htmlContentType={
    "Content-Type":"text/html"
}
cssContentType={
    "Content-Type":"text/css"
}
pngContentType={
    "Content-Type":"image/png"
}